'use client';
import {useMemo,useState} from 'react';
import type {Hall,Message,Snapshot} from '@/lib/types';
import {eventRows,hallZip,milesBetween,sizeCategory,validCutoffs,type Cutoffs} from '@/lib/prize-analysis';
import {MessageCheck} from '@/components/message-check';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
const money=(n:number|null)=>n===null?'Unknown':n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
type Point={lat:number;lng:number};
function Pick({label,value,values,onChange}:{label:string;value:string;values:string[];onChange:(s:string)=>void}){return <label>{label}<Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></label>}
export function CompetitiveAnalysis({snapshot,onOpen}:{snapshot:Snapshot;onOpen:(hall:Hall)=>void}){
 const [history,setHistory]=useState<Message[]>([]),[loading,setLoading]=useState(false),[coverage,setCoverage]=useState('Latest collected texts only. Load history for comparisons across dates.'),[error,setError]=useState('');
 const [query,setQuery]=useState(''),[minimum,setMinimum]=useState(''),[maximum,setMaximum]=useState(''),[date,setDate]=useState(''),[hb,setHb]=useState('All'),[size,setSize]=useState('All'),[sort,setSort]=useState('Prize: high to low'),[basis,setBasis]=useState('Advertised prizes'),[lead,setLead]=useState('All');
 const [draft,setDraft]=useState(['','','']),[cutoffs,setCutoffs]=useState<Cutoffs|null>(null),[thresholdError,setThresholdError]=useState('');
 const [zip,setZip]=useState(''),[radius,setRadius]=useState('50'),[geo,setGeo]=useState<{origin:Point;points:Record<string,Point>;zip:string;radius:number}|null>(null),[geoBusy,setGeoBusy]=useState(false),[geoError,setGeoError]=useState('');
 const messages=useMemo(()=>[...new Map([...history,...snapshot.messages,...snapshot.summaries.flatMap(s=>s.latest?[s.latest]:[])].filter(m=>m.kind==='promotion').map(m=>[m.id,m])).values()],[history,snapshot]);
 const allRows=useMemo(()=>eventRows(messages,snapshot.halls),[messages,snapshot.halls]);
 const rows=allRows.filter(r=>!r.analysis.cancelled).map(r=>{const z=hallZip(r.hall.address),point=z&&geo?.points[z];const distance=geo&&point?milesBetween(geo.origin,point):null;const clues=r.analysis.prizes.filter(p=>!['price','credit'].includes(p.kind)).map(p=>p.amount);const amount=basis==='Advertised prizes'?r.analysis.advertised:basis==='Conditional jackpots'?r.analysis.conditional:clues.length?Math.max(...clues):null;return {...r,distance,amount,category:sizeCategory(amount,cutoffs)}}).filter(r=>(r.hall.name+' '+r.hall.city+' '+r.hall.address).toLowerCase().includes(query.toLowerCase())&&(!minimum||r.amount!==null&&r.amount>=Number(minimum))&&(!maximum||r.amount!==null&&r.amount<=Number(maximum))&&(!date||r.analysis.eventDate===date)&&(hb==='All'||r.analysis.hotball===(hb==='HB / Hotball'))&&(size==='All'||r.category===size)&&(!geo||r.distance!==null&&r.distance<=geo.radius)&&(lead==='All'||lead==='Same day'&&r.firstLeadDays===0||lead==='In advance'&&r.firstLeadDays!==null&&r.firstLeadDays>0||lead==='Unknown'&&r.firstLeadDays===null)).sort((a,b)=>{
  if(sort==='Hall size'){const order=['Very large','Large','Medium','Small','Unassigned','Unknown'];return order.indexOf(a.category)-order.indexOf(b.category)||a.hall.name.localeCompare(b.hall.name);}
  if(sort==='Hall name')return a.hall.name.localeCompare(b.hall.name);
  if(sort==='Event date')return (a.analysis.eventDate||'9999').localeCompare(b.analysis.eventDate||'9999');
  if(sort==='Distance')return (a.distance??Infinity)-(b.distance??Infinity);
  if(a.amount===null)return b.amount===null?0:1;if(b.amount===null)return -1;return sort==='Prize: low to high'?a.amount-b.amount:b.amount-a.amount;
 });
 const amounts=rows.flatMap(r=>r.amount===null?[]:[r.amount]).sort((a,b)=>a-b);
 const median=amounts.length?(amounts[Math.floor((amounts.length-1)/2)]+amounts[Math.floor(amounts.length/2)])/2:null;
 async function load(){
  setLoading(true);setError('');const result=new Map<string,Message>();const targets=snapshot.summaries.filter(s=>s.count>0);let index=0,done=0;const failed:string[]=[];
  await Promise.all(Array.from({length:3},async()=>{while(index<targets.length){const target=targets[index++];try{let offset=0,more=true;while(more){const response=await fetch('/api/monitor?hall='+encodeURIComponent(target.hallId)+'&offset='+offset);const data=await response.json() as {messages:Message[];hasMore:boolean};if(!response.ok||!Array.isArray(data.messages))throw Error();for(const m of data.messages as Message[])result.set(m.id,m);more=!!data.hasMore;if(more&&!data.messages.length)throw Error();offset+=data.messages.length;}}catch{failed.push(target.hallId)}done++;setCoverage(`Loaded ${done} of ${targets.length} hall histories…`);}}));
  setHistory([...result.values()]);setLoading(false);setCoverage(`${result.size} unique historical texts loaded; ${targets.length-failed.length} of ${targets.length} hall histories complete.`);if(failed.length)setError(`${failed.length} hall histories could not be fully loaded. Results are partial; retry Load history.`);
 }
 async function locate(){
  if(!/^\d{5}$/.test(zip)){setGeoError('Enter a five-digit ZIP code.');return}setGeoBusy(true);setGeoError('');setGeo(null);
  const lookup=async(z:string):Promise<Point>=>{const r=await fetch('/api/locations?zip='+z);const b=await r.json() as Point&{error?:string};if(!r.ok)throw Error(b.error||'Location lookup failed');return b};
  try{const origin=await lookup(zip);const points:Record<string,Point>={[zip]:origin};const zips=[...new Set(allRows.flatMap(r=>{const z=hallZip(r.hall.address);return z?[z]:[]}))];let index=0,failed=0;await Promise.all(Array.from({length:4},async()=>{while(index<zips.length){const z=zips[index++];try{points[z]=await lookup(z)}catch{failed++}}}));setGeo({origin,points,zip,radius:Number(radius)});if(failed)setGeoError(`${failed} hall ZIP codes could not be located and are excluded. Retry to check them.`);}catch(e){setGeoError(e instanceof Error?e.message:'Location lookup failed');}finally{setGeoBusy(false)}
 }
 const unknownLocations=geo?allRows.filter(r=>{const z=hallZip(r.hall.address);return !z||!geo.points[z]}).length:0;
 return <section className="analysis-panel"><div className="section-label"><div><h2>Prize analysis</h2><p>Compare advertised amounts before choosing hall sizes.</p></div><Button disabled={loading} onClick={()=>void load()}>{loading?'Loading history…':'Load history'}</Button></div>
 <p className="analysis-note">{coverage} One row per hall and stated event date: latest text for prizes, earliest loaded text for advance notice. Cancelled events are excluded. Unknown dates remain separate. Shared-list promotions appear at each associated hall; amounts are never summed across halls.</p>
 {error&&<p role="alert" className="error">{error}</p>}
 <MessageCheck/><div className="analysis-filters"><label>Hall or location<Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Hall, city, ZIP"/></label><Pick label="Amount to compare" value={basis} onChange={setBasis} values={['Advertised prizes','Conditional jackpots','Largest prize clue (review)']}/><label>Minimum $<Input type="number" min="0" value={minimum} onChange={e=>setMinimum(e.target.value)}/></label><label>Maximum $<Input type="number" min="0" value={maximum} onChange={e=>setMaximum(e.target.value)}/></label><label>Event date<Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><Pick label="Hotball mention" value={hb} onChange={setHb} values={['All','HB / Hotball','No mention']}/><Pick label="Message timing" value={lead} onChange={setLead} values={['All','Same day','In advance','Unknown']}/><Pick label="Hall size" value={size} onChange={setSize} values={['All','Unassigned','Unknown','Small','Medium','Large','Very large']}/><Pick label="Sort" value={sort} onChange={setSort} values={['Prize: high to low','Prize: low to high','Hall name','Hall size','Event date','Distance']}/></div>
 <div className="analysis-location"><label>Near ZIP code<Input inputMode="numeric" maxLength={5} value={zip} onChange={e=>setZip(e.target.value)} placeholder="e.g. 95035"/></label><Pick label="Within miles" value={radius} onChange={setRadius} values={['50','100']}/><Button disabled={geoBusy} onClick={()=>void locate()}>{geoBusy?'Locating halls…':'Apply distance'}</Button><Button variant="outline" onClick={()=>{setGeo(null);setGeoError('')}} disabled={geoBusy}>Clear distance</Button></div>
 {geo&&<p className="analysis-note">Within {geo.radius} approximate straight-line miles of {geo.zip}, using ZIP centers. {unknownLocations} rows excluded because their location is unknown. Distances near the boundary need address verification. <a href="https://docs.zippopotam.us/docs/getting-started/" target="_blank" rel="noreferrer">Location source</a></p>}{geoError&&<p role="alert" className="error">{geoError}</p>}
 <details className="analysis-settings"><summary>Set hall-size cutoffs after reviewing the amounts</summary><p>Sizes describe the selected prize amount for that night. Until you apply cutoffs, halls stay unassigned. These settings apply to this open analysis.</p><div className="analysis-location">{['Medium starts at $','Large starts at $','Very large starts at $'].map((label,i)=><label key={label}>{label}<Input type="number" min="1" value={draft[i]} onChange={e=>setDraft(draft.map((v,j)=>j===i?e.target.value:v))}/></label>)}<Button onClick={()=>{const values=draft.map(Number);if(!validCutoffs(values)){setThresholdError('Enter three positive amounts, from lowest to highest.');return}setCutoffs(values);setThresholdError('');setSize('All')}}>Apply cutoffs</Button><Button variant="outline" onClick={()=>{setCutoffs(null);setSize('All')}}>Leave unassigned</Button></div>{thresholdError&&<p role="alert" className="error">{thresholdError}</p>}{cutoffs&&<p>Small: below {money(cutoffs[0])} · Medium: below {money(cutoffs[1])} · Large: below {money(cutoffs[2])} · Very large: {money(cutoffs[2])} or more.</p>}</details>
 <div className="analysis-stats"><div><b>{rows.length}</b><span>hall / event rows</span></div><div><b>{money(amounts[0]??null)}</b><span>lowest known amount</span></div><div><b>{money(median)}</b><span>median known amount</span></div><div><b>{money(amounts.at(-1)??null)}</b><span>highest known amount</span></div><div><b>{rows.length-amounts.length}</b><span>amounts unknown</span></div></div>
 <p className="analysis-note">Advertised amounts are claims from texts, not confirmed payouts. Conditional amounts require winning conditions and are shown separately. “Largest prize clue” helps explore unclear amounts and is not a nightly total. Open “Text & findings” to check details, prices, and uncertainty.</p>
 {!rows.length?<p className="notice">{messages.length?'No matching hall events. Adjust the filters or load more history.':'No promotional texts are available yet. Connect the message database, then load history to see real prize amounts.'}</p>:<Table><TableHeader><TableRow>{['Hall / city','Event / timing','Advertised prizes','Conditional amounts','Other amounts / review','Games / HB','Size','Evidence'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.hall.id+r.message.id}><TableCell><button className="analysis-hall" onClick={()=>onOpen(r.hall)}>{r.hall.name}</button><p>{r.hall.city}</p>{r.distance!==null&&<small>≈ {r.distance.toFixed(1)} miles</small>}</TableCell><TableCell>{r.analysis.eventDate||'Date needs review'}<p>{r.analysis.eventTime||'Start time unstated'}</p><small>{r.firstLeadDays===null?'Lead time unknown':r.firstLeadDays===0?'Texted same day':r.firstLeadDays>0?`Texted ${r.firstLeadDays} days ahead`:`Texted ${-r.firstLeadDays} days after`}</small></TableCell><TableCell>{money(r.analysis.advertised)}</TableCell><TableCell>{r.analysis.prizes.some(p=>p.kind==='conditional')?r.analysis.prizes.filter(p=>p.kind==='conditional').map((p,i)=><p key={i}>{money(p.amount)} {p.label||'conditional'}</p>):'Unknown'}</TableCell><TableCell>{r.analysis.prizes.filter(p=>['unknown','credit','per_game'].includes(p.kind)).map((p,i)=><p key={i}>{money(p.amount)} · {p.label||'Unclear'} · {p.kind==='credit'?'Credit promotion':p.kind==='per_game'?'Per strip game; nightly total unknown':'Rules need review'}</p>)}</TableCell><TableCell>{r.analysis.games??'Unknown'} games<p>{r.analysis.hotball?'HB / Hotball':'No HB mention'}</p></TableCell><TableCell>{r.category}</TableCell><TableCell><details><summary>Text & findings {r.analysis.warnings.length?'· review':''}</summary><p className="analysis-source">{r.message.body}</p><p>Received {new Date(r.message.receivedAt).toLocaleString('en-US',{timeZone:'America/Los_Angeles'})} Pacific</p><p>{r.analysis.dateBasis}</p><p>{r.textCount} texts for this date. First loaded notice: {new Date(r.firstMessage.receivedAt).toLocaleString('en-US',{timeZone:'America/Los_Angeles'})} Pacific.</p>{r.firstMessage.id!==r.message.id&&<p className="analysis-source">First notice: {r.firstMessage.body}</p>}{r.analysis.prizes.map((p,i)=><p key={i}>{money(p.amount)} · {p.label&&p.label+' · '}{p.kind}<br/>{p.evidence}</p>)}{r.analysis.warnings.map(w=><p key={w} className="analysis-warning">{w}</p>)}{r.hall.schedule&&<p>Published schedule: {r.hall.schedule.details} <a href={r.hall.schedule.sourceUrl} target="_blank" rel="noreferrer">Source</a></p>}</details></TableCell></TableRow>)}</TableBody></Table>}
 </section>;
}
