'use client';
import {useState} from 'react';
import type {Hall} from '@/lib/types';
import {safeWebUrl,type VendorReport} from '@/lib/vendor-research';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
export function VendorAnalysis({halls}:{halls:Hall[]}){
 const [query,setQuery]=useState(''),[reports,setReports]=useState<Record<string,VendorReport>>({}),[busy,setBusy]=useState<string|null>(null),[errors,setErrors]=useState<Record<string,string>>({});
 const matches=halls.filter(h=>(h.name+' '+h.city+' '+h.presales?.platform).toLowerCase().includes(query.toLowerCase()));
 async function inspect(hall:Hall){setBusy(hall.id);setErrors(old=>({...old,[hall.id]:''}));try{const r=await fetch('/api/vendors?hall='+encodeURIComponent(hall.id));const b=await r.json() as VendorReport&{error?:string};if(!r.ok)throw Error(b.error||'Research unavailable');setReports(old=>({...old,[hall.id]:b}));}catch(e){setErrors(old=>({...old,[hall.id]:e instanceof Error?e.message:'Research unavailable'}));}finally{setBusy(null)}}
 const link=(url:string,label:string)=>safeWebUrl(url)?<a href={safeWebUrl(url)!} target="_blank" rel="noreferrer">{label} ↗</a>:<span>{label}</span>;
 return <section className="analysis-panel"><h2>Ordering & payment vendors</h2><p>Check the hall’s website and purchase links for vendor evidence.</p><p className="analysis-note">An ordering vendor, a payment service, and the in-hall POS can be different companies. The merchant processor stays unknown unless public evidence identifies it. Checks read public pages and follow purchase links without placing an order.</p><Input aria-label="Find hall or vendor" placeholder="Find a hall, city, or recorded ordering vendor" value={query} onChange={e=>setQuery(e.target.value)} className="vendor-search"/><p>{matches.length} halls</p><div className="vendor-grid">{matches.map(h=>{const report=reports[h.id];return <article className="vendor-card" key={h.id}><h3>{h.name}</h3><p>{h.city}</p><dl><dt>Recorded advance ordering</dt><dd>{h.presales?.platform||'Unknown'}{h.presales?.url&&<> · {link(h.presales.url,'Sales page')}</>}<p>{h.presales?.details||'No ordering evidence recorded.'}</p>{h.presales?.verifiedAt&&<small>Recorded {h.presales.verifiedAt}</small>}</dd><dt>Merchant processor</dt><dd>{report?.findings.filter(f=>f.role==='Merchant processor').map(f=>f.name).join(', ')||'Unknown — public checkout clues do not confirm the merchant’s contract.'}</dd><dt>In-hall POS</dt><dd>{report?.findings.filter(f=>f.role==='POS').map(f=>f.name).join(', ')||'Unknown — online ordering alone does not identify the POS.'}</dd></dl>{h.website&&link(h.website,'Hall website')}<Button variant="outline" disabled={!!busy||!h.website&&!h.presales?.url} onClick={()=>void inspect(h)}>{busy===h.id?'Checking pages…':'Check vendor evidence'}</Button>{errors[h.id]&&<p role="alert" className="error">{errors[h.id]}</p>}{report&&<div className="vendor-report"><p>Checked {new Date(report.checkedAt).toLocaleString()} · {report.pages.length} readable pages</p>{report.findings.length?report.findings.map((f,i)=><div key={i}><strong>{f.role}: {f.name}</strong><p>{f.confidence} · {f.evidence}</p>{link(f.url,'Evidence')}</div>):<p>No vendor identified from readable pages.</p>}<details><summary>Pages checked & limitations</summary>{report.pages.map(p=><p key={p}>{link(p,p)}</p>)}{report.notes.map((n,i)=><p key={i}>{n}</p>)}</details></div>}</article>})}</div>{!matches.length&&<p className="notice">No matching halls.</p>}</section>;
}
